WordOps/WordOps

install, wo/cli/templates/locations-php7.mustache, wo/cli/templates/locations.mustache, wo/cli/templates/wpcommon-php7.mustache, wo/cli/templates/wpcommon.mustache
* letsencrypt validation in /var/www/html 
* new static files rules
* robots.txt fallback for WP
* harden nginx configurations
=> new nginx configurations

install
* create the folder /etc/nginx/conf.d
* create webp mapping configuration /etc/nginx/conf.d/webp.conf
=> fix $webp_uri variable on fresh install

CHANGELOG.md, README.md, install, setup.py, wo/cli/plugins/update.py, wo/cli/templates/22222.mustache, wo/cli/templates/locations-php7.mustache, wo/cli/templates/locations.mustache, wo/cli/templates/nginx-core.mustache, wo/cli/templates/php-hhvm.mustache, wo/cli/templates/php.mustache, wo/cli/templates/php7.mustache, wo/cli/templates/redis-hhvm.mustache, wo/cli/templates/redis-php7.mustache, wo/cli/templates/redis.mustache, wo/cli/templates/wpfc-hhvm.mustache, wo/cli/templates/wpfc-php7.mustache, wo/cli/templates/wpfc.mustache, wo/core/variables.py
- New Nginx query paramater handling (according to WP 5.0 guidelines)
- New changelog and README
- Improved install script
- Add WebP image support with Nginx mapping
- Nginx variable $webp_suffix on fresh install
- wo update command
=> Prioritary updates

CHANGELOG.md, install, wo/cli/plugins/site.py, wo/cli/plugins/site_functions.py, wo/cli/plugins/stack.py
* cleanup install
* update changelog
* fix user & email prompt during installation
=> Updating configuration

install
- Fix nginx configuration backup
=> Fix nginx configuration backup

install, wo/cli/plugins/stack.py
* fix wrong path for ssl.conf file used to secure WordOps backend
=> Fix ssl.conf for WordOps backend

wo/cli/plugins/update.py
- wo update subcommand display in commands list
=> Updating-configuration

install, setup.py, wo/cli/plugins/update.py, wo/core/variables.py
- nginx upgrade failure when running `wo update`
=> Hotfix for wo update

wo/cli/templates/map-wp.mustache
Don't cache edd_items_in_cart cookie and edd-sl (software licensing) requests.
=> Don't cache edd_items_in_cart and edd-sl requests

wo/cli/plugins/stack.py
- Packages list to debug log instead of info
=> list package to debug

wo/cli/plugins/stack.py
sudo wo stack purge --netdata was not working on my setup.
Uninstall script was wrong located. It is under another netdata folder as you can see in my PR.
I have manually triggered and uninstall netdata.
my setup is on Wordops v3.9.8.7 btw
=> netdata uninstall not work

.travis.yml, CHANGELOG.md, install, tests/init-file, tests/travis.sh, wo/cli/plugins/clean.py, wo/cli/plugins/debug.py, wo/cli/plugins/log.py, wo/cli/plugins/maintenance.py, wo/cli/plugins/site.py, wo/cli/plugins/site_functions.py, wo/cli/plugins/stack.py, wo/cli/plugins/stack_migrate.py, wo/cli/plugins/stack_pref.py, wo/cli/plugins/stack_services.py, wo/cli/plugins/stack_upgrade.py, wo/cli/plugins/sync.py, wo/cli/templates/acl.mustache, wo/cli/templates/fail2ban.mustache, wo/cli/templates/locations.mustache, wo/cli/templates/mime.mustache, wo/cli/templates/nginx-core.mustache, wo/cli/templates/wpcommon.mustache, wo/core/checkfqdn.py, wo/core/logwatch.py, wo/core/shellexec.py
- Rate limiter on wp-cron.php and xmlrpc.php
- mime.types template to handle missing extension ttf
- try_files directive for favicon
- additional settings for fail2ban
- Auto-apply bash-completion after install/update
- asynchronous installer to decrease install/update duration
- Several typo or syntax errors
- `wo  site` errors due to broken symlinks for access.log or error.log
- `wo clean` error due to unused memcached flag
=> Updating configurationcd

.travis.yml, CHANGELOG.md, README.md, install, tests/travis.sh, wo/cli/plugins/site.py, wo/cli/plugins/stack_upgrade.py, wo/core/shellexec.py, wo/core/sslutils.py
- sslutils error when trying to display SSL certificate expiration
=> SSL certificates expiration

.github/workflows/pypi.yml
=> Update and rename main.yml to pypi.yml

wo/cli/plugins/secure.py
Fixes #368 (missing space caused by concatenation of two lines).
I'm just assuming this is the best way to fix this, but I'm not familiar with the code so definitely good to get eyes on it
=> Fix typo in help text

README.md
Removing duplicated strings for README.md file: Apps & Tools: MySQLTuner
=> Removing duplicated strings for README.md file: Apps & Tools: MySQLTuner

wo/core/variables.py
Update wp-cli to latest v2.5.0
=> Update wp-cli to v2.5.0

.github/workflows/main.yml, wo/cli/plugins/debug.py, wo/cli/plugins/info.py, wo/cli/plugins/site_create.py, wo/cli/plugins/site_functions.py, wo/cli/plugins/site_update.py, wo/cli/plugins/stack.py, wo/cli/plugins/stack_pref.py, wo/cli/plugins/stack_services.py, wo/cli/plugins/stack_upgrade.py, wo/core/services.py, wo/core/variables.py
Added support for PHP8.0 and PHP8.1.
=> #348: PHP8

wo/cli/templates/cf-update.mustache
Fixes #420 
Added validation to IP files obtained from Cloudflare to ensure only valid IP blocks are output to Nginx configuration file.
=> #420 No error treatment to /opt/cf-update.sh

wo/cli/plugins/log.py
After dispensing with PHP 7.2 and adopting both PHP 7.3, 7.4, 8.0, 8.1 AND MariaDB.
You missed updating the log.py file to correct the new log file paths.
So, I fixed it and fixed it for everyone
Thanks for your efforts.
=> Fix wo log reset --all

wo/core/acme.py
=> Fixed a spelling mistake

README.md, config/bash_completion.d/wo_auto.rc, tests/travis.sh, wo/cli/plugins/info.py, wo/cli/plugins/site_functions.py, wo/cli/plugins/stack.py, wo/cli/plugins/stack_pref.py, wo/cli/plugins/stack_services.py, wo/cli/plugins/stack_upgrade.py, wo/cli/templates/upstream.mustache, wo/core/services.py, wo/core/variables.py
Added php8.2 to WO, on all scripts which mention php80 or php81.
=> #482: Add PHP 8.2 to WO

wo/cli/plugins/site_update.py, wo/cli/plugins/stack.py
A few typos were preventing PHP8.2 from working.
=> #486 Bugfix PHP 8.2 support

CHANGELOG.md, README.md, config/wo.conf, wo/core/variables.py
Update MariaDB to latest LTS version available as of now i.e. v10.11
=> Update MariaDB to latest LTS version

install, wo/core/variables.py
That's why I offer this changes #535 
Add support for Debian 12
Just fixed few variables
=> Add support for Debian 12

wo/cli/plugins/stack_migrate.py
Improve MariaDB upgrade process
=> Improve MariaDB migrate

tests/travis.sh, wo/cli/plugins/site_functions.py, wo/cli/plugins/stack.py, wo/cli/plugins/stack_pref.py, wo/cli/templates/proftpd.mustache
- Fix php configuration
- Fix netdata conf path
- Improve log display
=> Various fixes

wo/cli/templates/map-wp.mustache
=> do not cache wishlist

wo/cli/plugins/site_functions.py, wo/cli/plugins/site_update.py, wo/cli/plugins/stack_pref.py, wo/cli/templates/tweaks.mustache, wo/core/acme.py, wo/core/checkfqdn.py, wo/core/fileutils.py, wo/core/variables.py
- Fix WordOps create site duration : https://github.com/WordOps/WordOps/issues/624
- Fix WordOps install due to server ip check : https://github.com/WordOps/WordOps/issues/623
=> Fix reported issues

CHANGELOG.md, install
Update changelog and prepare for release v3.20.0
=> Update changelog and prepare for release v3.20.0

.github/workflows/main.yml, install, setup.py, wo/cli/plugins/stack_pref.py, wo/core/variables.py
- Prepare support for Ubuntu 24.04
- Cleanup wordops install with pip
- Fix [CVE-2024-34528](https://github.com/advisories/GHSA-23qq-p4gq-gc2g)
=> Fix CVE-2024-34528 and add support for Ubuntu 24.04

wo/cli/templates/wpsc.mustache
Fix issue https://github.com/WordOps/WordOps/issues/639
=> Fix wpsc template

README.md, install, wo/cli/plugins/info.py, wo/cli/plugins/site_functions.py, wo/cli/plugins/stack.py, wo/cli/plugins/stack_pref.py, wo/cli/plugins/stack_upgrade.py, wo/core/variables.py
- Fix netdata install/upgrade, always install deb packages
- Fix and cleanup wo info
- Always download lastest wp-cli
=> Fix netdata install/upgrade and wo info
