WordOps/WordOps

wo/core/variables.py
[Fix] 64 bit Server doesn't support architecture 'i386' for MariaDB Repo
This PR fixes the issue an i386 architecture error message on 64bit Server while doing the APT update. 
Error Msg: 
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.3/ubuntu bionic InRelease' doesn't support architecture 'i386'`
=> [Fix] 64 bit Server doesn't support architecture 'i386' for MariaDB Repo

wo/cli/templates/stub_status.mustache
Currently it uses php7.2-fpm.sock while the actual socket file name is php72-fpm.sock
=> Issue #81 update stub_status to php72-fpm.sock & avoid 502

install
1. make script executable or it won’t work
2. instead of writing to user’s dotfiles, create a symbolic link with the script alias.
=> fix cheat install

wo/cli/plugins/debug.py
`wo debug --php73=off` is not working because of using wrong php version.
=> correct php version for wo debug --php73=off

wo/cli/templates/wpcommon.mustache
This pull request replaces  #221 
Easy Digital Download files won't be able to be downloaded directly from the server. 
https://docs.easydigitaldownloads.com/article/682-protected-download-files-on-nginx
=> Protect Easy Digital Download files from being accessed directly.

wo/cli/templates/locations.mustache, wo/cli/templates/virtualconf.mustache
Enable valid reponse from https://domain.tld/.well-known/acme-challenge/ in case site uses Basic Auth.
If not set, a `wo site update domain.tld --le` fails.
=> Enable Letsencrypt installation on sites that use basic auth

wo/core/sslutils.py
`--allow-root` is missing from the `search-replace` part in `SSL.siteurlhttps`.
`--allow-root` is added to the other commands in this method.
=> Add --allow-root to search-replace in SSL.siteurlhttps.

wo/cli/templates/map-wp.mustache
Removed `/edd_action` as it's actually `/?edd_action`. a query string. They are removed by default.
Removed `/checkout` as we already have `/checkout/` (One of my plugins has the URL of /checkout-countdown../ and was never cached.) 
Added `/account/` as it's a common page that shouldn't be cached.
=> Updated caching rules

wo/cli/templates/22222.mustache
When viewing traffic on `domain.tld:22222/vts_status`, it makes sense to exclude traffic from the status page itself.
Reference:
https://github.com/vozlt/nginx-module-vts#to-calculate-traffic-except-for-status-page
=> Exclude the status page itself in traffic calculation

wo/cli/plugins/site_functions.py
Including AWS RDS MariaDB. See https://github.com/WordOps/WordOps/issues/263
Fixes #263.
GRANT statement that works for all MySQL/MariaDB variants.
AWS RDS MariaDB security policies blocks "all privileges" to be granted.
My personal opinion is that this is also a good security practice to request specifically that needed privileges. Especially as WordPress and its plugins have been targeted for attacks.
=> Fix: GRANT works for all MySQL/MariaDB variants

wo/cli/plugins/stack_pref.py, wo/cli/templates/avif.mustache, wo/cli/templates/wpcommon.mustache
Add the [AVIF](https://aomediacodec.github.io/av1-avif/) support to Nginx stack. It should be simple as WebP integrate and need nothing special to config.
The type of AVIF image should be `octet-stream` then you're success as implement AVIF.
=> Add avif support

CHANGELOG.md, README.md, install, setup.py, tests/travis.sh, wo/cli/plugins/site_functions.py, wo/cli/templates/proftpd-tls.mustache, wo/core/mysql.py, wo/core/variables.py
- Add avif (AV1 Image Format) support into Nginx ([PR #314](https://github.com/WordOps/WordOps/pull/314))
- Use zstd instead of pigz for archive compression
- Exclude Nginx_vts status page from traffic calculation ([PR #294](https://github.com/WordOps/WordOps/pull/294))
- fail2ban install without Nginx
- Grant MySQL permissions on all MySQL/MariaDB variant ([PR #285](https://github.com/WordOps/WordOps/pull/285))
- PHP PECL extensions and PHP 8.0 issues
=> WordOps Maintenance Release v3.12.3

install
update install script so that acme.sh will use LetsEncrypt instead of ZeroSSL when the `--letsencrypt` parameter is used.
Fixes #387. Updates install script so that acme.sh will use LetsEncrypt instead of ZeroSSL in new installs.
Current behaviour is for acme.sh to use ZeroSSL as default CA when the `--letsncrypt` parameter is used. This is confusing and unintuitive for users. Adding this line to the install script ensures that when the WordOps user enters `--letsencrypt`, acme.sh will actually use LetsEncrypt.
=> fix acme.sh to use letsencrypt by default in new installs

wo/core/variables.py
Support arm64 architecture
Enables mysqlclient / mariadb-client to be installed in e.g. AWS Graviton2 instances.
=> fix: Support arm64 architecture (e.g. AWS Graviton2)

wo/cli/templates/map-wp.mustache
Exclude PWA Service Worker file from cache. It's located at /wp.serviceworker
=> Cache exception for PWA Service Worker

wo/cli/templates/map-wp.mustache
- Escape `.` characters in regex strings by putting a `\` in front of them (`\.`).
- Replace `*` characters in regex strings that should represent wildcards with `.*`.
=> Escaping of metacharacters in regex strings in wo/cli/templates/map-wp.mustache 

wo/cli/templates/cf-update.mustache
In the previous commit I forgot to add the `real_ip_header CF-Connecting-IP` directive to the generated configuration file.
Also, I added a `nginx -t` before the `service nginx reload`.
=> #420: No error treatment to /opt/cf-update.sh

wo/cli/templates/tweaks.mustache
Nginx 1.19.7+ Deprecated HTTP/2 variables.
If you're using these deprecated HTTP/2 variables in Nginx 1.19.7+ vhosts, on Nginx service restarts or Nginx config checks (nginx -t), you'll get Nginx warning messages as such but the Nginx service will still start and run Nginx server fine. Example warning message:
```
root@wooserv:~# nginx -t
nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/conf.d/tweaks.conf:4
nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/conf.d/tweaks.conf:5
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
``` …
=> fix obsolete warnings logged

wo/cli/templates/locations.mustache
Seems there is an issue with these changes. This is what the output of `https://www.example.com/.well-known/traffic-advice` looks like with WO 3.15.3 :
```
[\{
"user_agent": "prefetch-proxy",
"google_prefetch_proxy_eap": \{
"fraction": 1.0
\}
\}]
```
**Here is the expected output for a valid configuration**:
```
[{
"user_agent": "prefetch-proxy",
"google_prefetch_proxy_eap": {
"fraction": 1.0
}
}]
```
=> fix prefetch-proxy configuration

wo/cli/plugins/stack_services.py
* Fix wrong else statements in stack_services.py.
I've only installed PHP 8.0 and I see (`PHP8.0-FPM is not installed` ???):
```
PHP7.2-FPM is not installed
PHP7.3-FPM is not installed
PHP8.0-FPM is not installed
PHP7.4-FPM is not installed
Testing Nginx configuration     [OK]
Restarting Nginx                [OK]
Restarting php8.0-fpm           [OK]
Restarting mariadb              [OK]
Restarting netdata              [OK]
```
=> Fix wrong else statements in stack_services.py

wo/cli/templates/locations.mustache, wo/cli/templates/wpcommon.mustache
Fixes #361
Currently cache expiry of css and js is set to 30d. However Google pagespeed expect it to be at least 1 year as per https://web.dev/uses-long-cache-ttl/.
=> Set cache expiry of css and js files to 1 year

wo/core/sendmail.py
When sending an email, multiple files are opened and read but never closed. While this will be GCed on exit, it is always a good idea to close open files.
The code of the `WOSendMail` function is similar to the code in this [answer](https://stackoverflow.com/a/16509278) and the bug is fixed in the second version of the answer.
=> bug fix: close file after reading

wo/cli/templates/map-wp.mustache
The full-page caching set up by WordOps will incorrectly cache some authenticated responses to the WordPress REST API.
1. Set up a WordOps site with the `--wpredis` option (and perhaps others) to enable full-page caching. Let's say it's `https://yoursite.com`.
2. Log in to wp-admin as an administrator user (let's say the username is `administrator`).
3. Go to Users > Profile and create a new application password under the Application Passwords section. Let's say it's `abcd efgh ijkl mnop qrst uvwx`.
4. Create a new post from the wp-admin interface. Save it as a draft; do not publish it. Record its ID (let's say it's `999`).
5. Generate a base64 authentication string in the terminal using the values from the previous steps: `echo -n 'administrator:abcd efgh ijkl mnop qrst uvwx' | base64`. …
=> Do not cache requests with Authorization header set

wo/cli/templates/force-ssl.mustache
Just fix missing braces on force-ssl.mustache causing adding SSL to websites to fail on WO 3.19.
=> #587: fix missing braces on force-ssl.mustache

wo/cli/plugins/info.py, wo/cli/plugins/stack_services.py, wo/core/services.py
- Adds php8.3 info to fix missing details on `wo info` command.
- Adds php8.3 to status check, to fix empty php 8.3 on `wo stack status` command.
- Fixes incorrect log `Fix PHP{version}-FPM is not installed` issue #603 
Note, however, that the PHP service is being added 2 times, I think this wasn't intended on https://github.com/WordOps/WordOps/pull/559, please let me know if we should get rid of one of those conditionals.
```php
if pargs.php:
for parg_version, version in WOVar.wo_php_versions.items():
if os.path.exists(f'{wo_system}' + f'php{version}-fpm.service'):
services = services + [f'php{version}-fpm']
for parg_version, version in WOVar.wo_php_versions.items():
if (getattr(pargs, parg_version, False) and
os.path.exists(f'{wo_system}' + f'php{version}-fpm.service')):
services = …
```
=> Fix PHP{version}-FPM is not installed and fix support for php 8.3

install
Added null check on user so that user will be initiated as WordOps when installing with --silent flag if linux $USER in empty like in docker in my case
```bash
if [ "$wo_force_install" = "y" ]; then
[ ! -f "$HOME/.gitconfig" ] && {
bash -c 'echo -e "[user]\n\tname = $USER\n\temail = root@$HOSTNAME.local" > $HOME/.gitconfig';
}
fi
```
```bash
Copy code
if [ "$wo_force_install" = "y" ]; then
USER_OR_WORDOPS=${USER:-WordOps}
[ ! -f "$HOME/.gitconfig" ] && {
bash -c "echo -e \"[user]\n\tname = $USER_OR_WORDOPS\n\temail = root@$HOSTNAME.local\" > $HOME/.gitconfig";
}
fi
```
Last Thursday, I encountered an issue installing WordOps in a Docker container using the `--silent` flag. The installation process failed because the `$USER` variable was not set properly in the Docker environment. This …
=> added null check on user

wo/core/download.py
This PR fixes a bug in `wo/core/download.py` where an `AttributeError` occurs if a `ConnectionError` does not contain a `reason` attribute. This can happen in DNS resolution failures or similar network issues.
Instead of using `e.reason`, we now use a more robust logging method:
```python
Log.debug(self, f"[{type(e).__name__}] {str(e)}")
```
This ensures that all request exceptions are handled gracefully without additional tracebacks.
=> Fix AttributeError in WODownload when ConnectionError lacks reason

.github/workflows/pypi.yml
Potential fix for [https://github.com/WordOps/WordOps/security/code-scanning/7](https://github.com/WordOps/WordOps/security/code-scanning/7)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the minimal permissions required. Since this workflow primarily interacts with the repository contents to build and publish a package, it only needs `contents: read`. This ensures that the workflow does not inadvertently gain unnecessary write permissions.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 7: Workflow does not contain permissions
